const dynamoScanItemsResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: "4R0KJUIA3RB0RJ94HKVLH0KITFVV4KQNSO5AEMVJF66Q9ASUAAJG",
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  Attributes: {},
  ConsumedCapacity: undefined,
  ItemCollectionMetrics: undefined,
};
const dynamoUpdateItemResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: "4R0KJUIA3RB0RJ94HKVLH0KITFVV4KQNSO5AEMVJF66Q9ASUAAJG",
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  Attributes: {},
  ConsumedCapacity: undefined,
  ItemCollectionMetrics: undefined,
};
const cognitoClientResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: "e23f4c42-73bf-4907-94f8-57c0780af4d2",
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
};
const sesClientResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: "59af8813-1bc2-4a32-9b85-8b7b5e94555d",
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  MessageId: "0100017d36765409-98230f46-7fb2-4977-b8fa-6d9cc017bdc8-000000",
};
const snsClientResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: "a381566e-d60d-5d2f-a343-0c7ffd215d24",
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  MessageId: "82513ae6-aabc-5cb2-8141-60f781902cb9",
  SequenceNumber: undefined,
};
const s3ClientHeadResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId:
      "xChA8GId7TkygSmFzVlFEC0SOVezbJMqolkwjGhM4dAZI1wN3I/EezOz1I4g4SSRrozTDRoKIFk=",
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  AcceptRanges: "bytes",
  ArchiveStatus: undefined,
  BucketKeyEnabled: undefined,
  CacheControl: undefined,
  ContentDisposition: undefined,
  ContentEncoding: undefined,
  ContentLanguage: undefined,
  ContentLength: 446,
  ContentType: "application/octet-stream",
  DeleteMarker: undefined,
  ETag: '"cacc2f6bdfd7cc486718db4f732cb474"',
  Expiration: undefined,
  Expires: undefined,
  LastModified: "2021-05-28T02:39:17.000Z",
  Metadata: {
    "alt-name": "fitbit-access-tokens",
    "content-type": "application/json",
  },
  MissingMeta: undefined,
  ObjectLockLegalHoldStatus: undefined,
  ObjectLockMode: undefined,
  ObjectLockRetainUntilDate: undefined,
  PartsCount: undefined,
  ReplicationStatus: undefined,
  RequestCharged: undefined,
  Restore: undefined,
  SSECustomerAlgorithm: undefined,
  SSECustomerKeyMD5: undefined,
  SSEKMSKeyId: undefined,
  ServerSideEncryption: undefined,
  StorageClass: undefined,
  VersionId: undefined,
  WebsiteRedirectLocation: undefined,
};
const s3ClientGetResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId:
      "58lUtZjhPEZk2ifL9IFWn2MdmxP0RUCaSMJ45FvyuHn92Mtdp0JyyOzWwTnnvARcbXrcUNZ3/mM=",
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  AcceptRanges: "bytes",
  Body: {},
  BucketKeyEnabled: undefined,
  CacheControl: undefined,
  ContentDisposition: undefined,
  ContentEncoding: undefined,
  ContentLanguage: undefined,
  ContentLength: 446,
  ContentRange: undefined,
  ContentType: "application/octet-stream",
  DeleteMarker: undefined,
  ETag: '"cacc2f6bdfd7cc486718db4f732cb474"',
  Expiration: undefined,
  Expires: undefined,
  LastModified: "2021-05-28T02:39:17.000Z",
  Metadata: {
    "alt-name": "fitbit-access-tokens",
    "content-type": "application/json",
  },
  MissingMeta: undefined,
  ObjectLockLegalHoldStatus: undefined,
  ObjectLockMode: undefined,
  ObjectLockRetainUntilDate: undefined,
  PartsCount: undefined,
  ReplicationStatus: undefined,
  RequestCharged: undefined,
  Restore: undefined,
  SSECustomerAlgorithm: undefined,
  SSECustomerKeyMD5: undefined,
  SSEKMSKeyId: undefined,
  ServerSideEncryption: undefined,
  StorageClass: undefined,
  TagCount: undefined,
  VersionId: undefined,
  WebsiteRedirectLocation: undefined,
};
const s3ClientPutResponse = {
  $metadata: {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId:
      "cOZR70i8Oj/90mSc4+Ed0FvliZ7b8V653HU/VafphprwTL0h2MiwWtdgUyUBU4UreTLBmHmBnzg=",
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0,
  },
  BucketKeyEnabled: undefined,
  ETag: '"334ebb72d2bebc735809474950a24eea"',
  Expiration: undefined,
  RequestCharged: undefined,
  SSECustomerAlgorithm: undefined,
  SSECustomerKeyMD5: undefined,
  SSEKMSEncryptionContext: undefined,
  SSEKMSKeyId: undefined,
  ServerSideEncryption: undefined,
  VersionId: undefined,
};
const ebPutEventResponse = {
  $metadata: {
    httpStatusCode: 200,
  },
};
module.exports = {
  dynamoUpdateItemResponse,
  dynamoScanItemsResponse,
  cognitoClientResponse,
  sesClientResponse,
  snsClientResponse,
  s3ClientHeadResponse,
  s3ClientGetResponse,
  s3ClientPutResponse,
  ebPutEventResponse,
};
